### ISSUE TITLE
Trình Bịp Lắm

### ISSUE THREAD

**Issue by daivuongktx13** [nvtrinh2001/placemark-svelte#1]
Có quả project svelte đỉnh như thế này cơ mà 🥇. Cấu trúc chuẩn k cần chỉnh.

**Comment by nvtrinh2001** [comment]
> Có quả project svelte đỉnh như thế này cơ mà 🥇. Cấu trúc chuẩn k cần chỉnh.
> 
> 

Quên hết ròi 🥲 không hiểu sao viết được luôn :vv
